# Generated by Django 2.0.5 on 2018-06-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('RateID', models.BigAutoField(primary_key=True, serialize=False)),
                ('SourceCode', models.CharField(max_length=50)),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('SellPrice', models.DecimalField(decimal_places=6, max_digits=15)),
                ('BuyPrice', models.DecimalField(decimal_places=6, max_digits=15)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publised')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
